spring:
  application:
    name: service-nosql
  main:
    banner-mode: "off"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
      config:
        enabled: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-profile-stats

server:
  port: 8200
