spring:
  application:
    name: service-nosql
  main:
    banner-mode: "off"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
      config:
        enabled: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: "user_profile_stats"
#      password: "1234"
#      username: "user"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-profile-stats
    topic:
      user-profile: user-profile-topic
server:
  port: 8200
