spring:
  application:
    name: example-service
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: true
  datasource:
    maximum-pool-size: 100
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
        hibernate:
          show_sql: false
          use_sql_comments: false
          format_sql: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
      config:
        enabled: true
server:
  port: 8100
