spring:
  application:
    name: gateway
  main:
    banner-mode: "off"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
      config:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 2001
service:
  userprofile: service-rdbms
